spring:
  application:
    name: test-service
  liquibase:
    change-log: db/db.changelog.yaml
    liquibase-schema: public
    enabled: false
  datasource:
    url: jdbc:postgresql://ep-dark-waterfall-a24e6tlj-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
    username: user
    password: npg_H6UYNni1Mljp
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
